# Generated by Django 4.2.4 on 2023-12-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yes24Best200801202311',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.TextField(blank=True, null=True)),
                ('yy', models.BigIntegerField(blank=True, null=True)),
                ('mon', models.BigIntegerField(blank=True, null=True)),
                ('title_h', models.TextField(blank=True, null=True)),
                ('title_f', models.TextField(blank=True, null=True)),
                ('title_m', models.TextField(blank=True, null=True)),
                ('title_e', models.TextField(blank=True, null=True)),
                ('detail_link', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('pub_date', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('n_reviews', models.TextField(blank=True, null=True)),
                ('review_link', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yes24best200801_202311',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yes24BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.TextField(blank=True, null=True)),
                ('page', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('book_intro', models.TextField(blank=True, null=True)),
                ('pub_book_intro', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yes24_book_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Yes24OneLineReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.TextField(blank=True, null=True)),
                ('one_line_review', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yes24_one_line_reviews',
                'managed': False,
            },
        ),
    ]
