# Generated by Django 4.2.4 on 2023-12-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yes24', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yes24Bestlist',
            fields=[
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('book_id', models.TextField(primary_key=True, serialize=False)),
                ('yy', models.BigIntegerField(blank=True, null=True)),
                ('mon', models.BigIntegerField(blank=True, null=True)),
                ('title_h', models.TextField(blank=True, null=True)),
                ('title_m', models.TextField(blank=True, null=True)),
                ('title_e', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('pub_date', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('page', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('pub_book_intro', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yes24bestlist',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Yes24Best200801202311',
        ),
        migrations.DeleteModel(
            name='Yes24BookDetail',
        ),
        migrations.DeleteModel(
            name='Yes24OneLineReviews',
        ),
    ]
